#!/bin/bash
# Respring apos instalar o bypass
if [ -x /var/jb/usr/bin/sbreload ]; then
    /var/jb/usr/bin/sbreload
elif [ -x /usr/bin/sbreload ]; then
    /usr/bin/sbreload
elif [ -x /var/jb/usr/bin/killall ]; then
    /var/jb/usr/bin/killall -9 SpringBoard
else
    killall -9 SpringBoard
fi
exit 0